version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    # Limit to security updates and patch versions to avoid breaking changes
    open-pull-requests-limit: 10
