# GoReleaser configuration for dockerutilities
# This file configures automated releases with cross-platform builds
# Optimized for performance and enhanced changelog generation

# Pre-build hooks for validation and preparation
before:
  hooks:
    - go mod tidy
    - go mod verify
    - go vet ./...
    - go test -v ./...

# Build configuration optimized for performance
builds:
  - env:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: dockerutilities
    ldflags:
      - -s -w
      - -X github.com/smiller333/dockerutilities/src/version.Version={{.Version}}
      - -X github.com/smiller333/dockerutilities/src/version.GitCommit={{.Commit}}
      - -X github.com/smiller333/dockerutilities/src/version.BuildTime={{.Date}}
    hooks:
      pre: |
        echo "Building {{ .Os }}/{{ .Arch }} binary..."
        echo "Version: {{ .Version }}"
        echo "Commit: {{ .Commit }}"
      post: |
        echo "Built binary for {{ .Os }}/{{ .Arch }}"
        # Enhanced binary validation
        if [ -f "{{ .Path }}" ]; then
          echo "Binary size: $(stat -c%s {{ .Path }}) bytes"
          # Test version command and basic functionality
          if [ "{{ .Os }}" = "linux" ] || [ "{{ .Os }}" = "darwin" ]; then
            chmod +x {{ .Path }}
            echo "Testing binary functionality..."
            {{ .Path }} version 2>/dev/null || echo "Version command not available"
            {{ .Path }} --help 2>/dev/null || echo "Help command not available"
          fi
        fi

# Enhanced archive configuration with improved naming and organization
archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}-
      {{- title .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - docs/release-notes-template.md
      - docs/automated-build-planning.md
    # Enhanced file organization
    # Note: meta section is not supported in current GoReleaser version
    # File organization is handled by naming template and included files

# Enhanced changelog configuration
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch
      - '^wip:'
      - '^temp:'
    include:
      - '^feat:'
      - '^fix:'
      - '^improve:'
      - '^perf:'
      - '^refactor:'
      - '^security:'
      - '^breaking:'

# Enhanced release configuration with proper descriptions
release:
  # GitHub release settings
  github:
    owner: smiller333
    name: dockerutilities
  # Enhanced release notes template integration
  header: |
    {{ if .IsPatch }}
    ## 🐛 Bug Fix Release
    {{ else if .IsMinor }}
    ## 🎉 Feature Release
    {{ else }}
    ## ⚠️ Major Release
    {{ end }}
    
    {{ if .IsPrerelease }}
    ### 🧪 Development Release
    This is a development release for testing purposes. Not recommended for production use.
    {{ end }}
    
    **Release Date**: {{ .Date }}
    **Commit**: {{ .Commit }}
    **Go Version**: {{ .Env.GO_VERSION }}
    
    ---
  footer: |
    ---
    
    ### 📋 Installation
    
    Download the appropriate binary for your platform:
    
    **Linux (x86_64)**: `dockerutilities-{{ .Version }}-linux-x86_64`
    **Linux (ARM64)**: `dockerutilities-{{ .Version }}-linux-arm64`
    **macOS (Intel)**: `dockerutilities-{{ .Version }}-darwin-x86_64`
    **macOS (Apple Silicon)**: `dockerutilities-{{ .Version }}-darwin-arm64`
    **Windows (x86_64)**: `dockerutilities-{{ .Version }}-windows-x86_64.zip`
    **Windows (ARM64)**: `dockerutilities-{{ .Version }}-windows-arm64.zip`
    
    ### 🔐 Verification
    
    All binaries are signed and verified. You can verify the integrity using:
    
    ```bash
    # Download checksums file
    curl -LO https://github.com/smiller333/dockerutilities/releases/download/{{ .Tag }}/checksums.txt
    
    # Verify binary (replace with your platform)
    sha256sum -c checksums.txt
    ```
    
    ### 🔗 Quick Links
    - [Documentation](https://github.com/smiller333/dockerutilities#readme)
    - [Issues](https://github.com/smiller333/dockerutilities/issues)
    - [Discussions](https://github.com/smiller333/dockerutilities/discussions)
    
    ### 📝 Release Notes Template
    For detailed release notes and guidelines, see [docs/release-notes-template.md](https://github.com/smiller333/dockerutilities/blob/main/docs/release-notes-template.md)

# Enhanced checksums configuration
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
  # Note: GPG signature support can be added in future GoReleaser versions
  # Current version supports basic SHA256 checksums

# Docker configuration (prepared for Phase 4)
# dockers:
#   - image_templates:
#       - "ghcr.io/smiller333/dockerutilities:{{ .Version }}"
#       - "ghcr.io/smiller333/dockerutilities:latest"
#     dockerfile: Dockerfile
#     use: buildx
#     build_flag_templates:
#       - "--platform=linux/amd64"
#       - "--platform=linux/arm64"
#     extra_files:
#       - README.md
#       - LICENSE
    # Note: Docker hooks are not supported in current GoReleaser version
    # Docker validation will be handled in GitHub Actions workflow
